# Generated by Django 6.0.7 on 2026-09-21 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(choices=[('phishing_simulator', 'Phishing'), ('password_cracker', 'Password Security'), ('network_defense', 'Network Defense'), ('cryptography', 'Cryptography'), ('osint', 'OSINT')], db_index=True, max_length=50)),
                ('source_content', models.TextField(help_text='Only knowledge source for AI generation. Stored as a snapshot.')),
                ('source_language', models.CharField(choices=[('same_as_source', 'Same as Source'), ('en', 'English'), ('bn', 'বাংলা')], default='same_as_source', max_length=20)),
                ('output_language', models.CharField(choices=[('same_as_source', 'Same as Source'), ('en', 'English'), ('bn', 'বাংলা')], default='same_as_source', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('total_sets', models.PositiveSmallIntegerField(default=10)),
                ('normal_sets', models.PositiveSmallIntegerField(default=7)),
                ('simulation_sets', models.PositiveSmallIntegerField(default=3)),
                ('questions_per_set', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING', 'Generating'), ('REVIEW', 'Ready for review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('ai_provider', models.CharField(blank=True, default='', max_length=50)),
                ('ai_model', models.CharField(blank=True, default='', max_length=100)),
                ('generation_version', models.PositiveIntegerField(default=1)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Bank',
                'verbose_name_plural': 'Question Banks',
                'ordering': ['-created_at'],
            },
        ),
    ]
