# Generated by Django 6.0.7 on 2026-09-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_ai_question_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='generation_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
