# Generated by Django 6.0.7 on 2026-09-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_generation_version_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed')], default='mixed', help_text='Customize Set difficulty mode. Mixed → CyberQuest balanced blueprint. Beginner/Intermediate/Advanced → all questions that level.', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='questions_per_set',
            field=models.PositiveSmallIntegerField(default=10, help_text='Customize Set: number of questions per set. With difficulty=Mixed and 5 questions → 2 Beginner + 2 Intermediate + 1 Advanced.'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING', 'Generating'), ('REVIEW', 'Ready for review'), ('PARTIAL', 'Partial — needs repair'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
