# Generated by Django 6.0.7 on 2026-09-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_partial_status_and_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='attempt_mcq_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='MCQ slots per attempt (must sum with simulations to attempt_question_count).'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='attempt_question_count',
            field=models.PositiveSmallIntegerField(default=5, help_text='Questions shown per student attempt when using balanced selection.'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='attempt_simulation_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='Simulation slots per attempt (independent of difficulty labels).'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='questions_per_set',
            field=models.PositiveSmallIntegerField(default=10, help_text='Customize Set: number of questions per generated set. With difficulty=Mixed and 5 questions → 2 Beginner + 2 Intermediate + 1 Advanced.'),
        ),
    ]
