# Generated by Django 6.0.7 on 2026-09-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0004_balanced_selection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='output_language',
            field=models.CharField(choices=[('same_as_source', 'Same as Source'), ('en', 'English'), ('bn', 'বাংলা')], default='en', help_text='Target language for generated questions. Comes from this selection, not from the source text. English stays English even when the source is Bangla.', max_length=20),
        ),
    ]
