# Generated by Django 6.0.7 on 2026-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0005_output_language_default_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='generation_completed',
            field=models.PositiveIntegerField(default=0, help_text='Valid questions accepted so far during the current run.'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='generation_requested',
            field=models.PositiveIntegerField(default=0, help_text='Questions requested for the current run.'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='generation_stage',
            field=models.CharField(blank=True, default='', help_text='Current honest stage label while generation is running. Not a percentage.', max_length=120),
        ),
    ]
