"""
Expanded question pools for the 5 set-based courses.
Used to seed Question rows (idempotent by prompt+course).
"""

from .quiz_data import QUIZ_GAMES

SET_META = {
    "phishing_simulator": {"title": "Phishing Simulator", "emoji": "📧"},
    "password_cracker": {"title": "Password Cracker Challenge", "emoji": "🔑"},
    "network_defense": {"title": "Network Defense", "emoji": "🛡️"},
    "cryptography": {"title": "Cryptography Challenge", "emoji": "🔐"},
    "osint": {"title": "OSINT Investigation", "emoji": "🕵️"},
}


def _q(prompt, options, correct_index, explanation, wrong_feedback="", correct_feedback=""):
    return {
        "prompt": prompt,
        "options": options,
        "correct_index": correct_index,
        "explanation": explanation,
        "wrong_feedback": wrong_feedback or (
            f"Not quite. The correct answer is: {options[correct_index]}."
        ),
        "correct_feedback": correct_feedback or "Correct!",
    }


EXTRA_POOL = {
    "phishing_simulator": [
        _q(
            "From: it-support@corp-secure-mail.example\nSubject: Password expires in 1 hour\n\n"
            "\"Click below to keep access or your account will be locked.\"",
            ["This is a phishing email", "This is a legitimate email"], 0,
            "Lookalike external domain plus countdown urgency is a classic phishing pattern.",
            "The domain is not a trusted internal IT domain, and urgency is used to skip verification.",
        ),
        _q(
            "An email asks you to 'confirm your password' by replying in plain text. What should you do?",
            ["Reply with the password so IT can help", "Ignore/report — legitimate teams never ask this",
             "Forward it to friends for advice", "Call the number printed in the email footer"], 1,
            "No legitimate organization asks for passwords over email.",
            "Sharing a password by reply exposes the account immediately.",
        ),
        _q(
            "Which signal is MOST suspicious in an invoice email?",
            ["A PDF attachment from a known vendor portal", "A sudden change of bank details with urgency",
             "A polite thank-you note", "A link to the vendor's normal website"], 1,
            "Sudden payment-detail changes under pressure are common BEC/phishing tactics.",
            "Urgency around new bank details is a major red flag.",
        ),
        _q(
            "Hovering a 'Reset Password' button shows https://fictional-login.example while the text says microsoft.com. This means:",
            ["The link is safe because the button text is trusted", "Displayed text and destination differ — treat as suspicious",
             "Hovering is illegal", "You should click to verify"], 1,
            "Always check the real destination; display text can be spoofed.",
            "Mismatch between label and destination is a phishing indicator.",
        ),
        _q(
            "A colleague gets an email from 'the CEO' asking for gift cards privately. Best first response?",
            ["Buy the cards immediately", "Verify via a known separate channel before acting",
             "Reply with card codes", "Post the request in a public chat"], 1,
            "CEO fraud relies on urgency and secrecy — verify out-of-band.",
            "Acting on an unverified executive request is unsafe.",
        ),
        _q(
            "Which is a stronger phishing defense for end users?",
            ["Opening every attachment quickly", "Checking sender domain and unexpected requests before acting",
             "Disabling all email", "Reusing one password everywhere"], 1,
            "Slow down and verify sender/context before clicking or sharing data.",
            "Speed without verification favors attackers.",
        ),
        _q(
            "From: alerts@amaz0n-shipping.example\nSubject: Delivery failed\n\n\"Confirm address within 24 hours.\"",
            ["This is a phishing email", "This is a legitimate email"], 0,
            "Misspelled brand domain and delivery urgency are phishing hallmarks.",
            "amaz0n-style domains are lookalikes — do not trust them.",
        ),
        _q(
            "A real-looking login page after an email click asks for your password. Safest action?",
            ["Enter credentials to continue", "Close it and open the site via a bookmark/known URL",
             "Email your password to security", "Share a screenshot of your password manager"], 1,
            "Navigate to known sites yourself; email-driven login pages may be fake.",
            "Typing credentials into an email-driven page risks credential theft.",
        ),
        _q(
            "Which subject line is MORE suspicious?",
            ["Weekly team notes", "FINAL WARNING: account deleted tonight unless you verify NOW",
             "Meeting moved to 3pm", "Office closed Friday"], 1,
            "Extreme urgency and threats are designed to bypass careful reading.",
            "Threat + immediate action is a social-engineering pattern.",
        ),
        _q(
            "Spear phishing differs from generic phishing mainly because it:",
            ["Never uses email", "Is tailored to a specific person or role",
             "Only targets printers", "Cannot be reported"], 1,
            "Spear phishing uses personal/context details to appear trustworthy.",
            "Targeted personalization is the distinguishing factor.",
        ),
        _q(
            "An attachment named invoice.exe arrives unexpectedly. Best action?",
            ["Open it to inspect", "Do not open — report to security",
             "Rename to .pdf and open", "Forward to everyone"], 1,
            "Unexpected executables are high risk; report instead of opening.",
            "Opening unknown executables can compromise the device.",
        ),
        _q(
            "Multi-factor authentication helps against phishing mainly by:",
            ["Making passwords unnecessary forever", "Adding a second factor if a password is stolen",
             "Encrypting all emails automatically", "Blocking all external mail"], 1,
            "MFA reduces account takeover when credentials leak — it is not perfect against all MFA phishing.",
            "MFA is an extra barrier, not a reason to ignore phishing signs.",
        ),
        _q(
            "From: noreply@github.com\nSubject: Security alert — new SSH key\n\n\"If this wasn't you, review security settings on github.com.\"",
            ["This is a phishing email", "This is a legitimate email"], 1,
            "Trusted domain and guidance to use the normal site (no credential harvest in-email) looks legitimate.",
            "This pattern matches normal security notices.",
        ),
        _q(
            "Why is 'Click here to disable your antivirus' in an email dangerous?",
            ["Antivirus is never useful", "It tries to remove a key defense",
             "It improves performance safely", "It is required by law"], 1,
            "Attackers want defenses disabled before delivering malware.",
            "Disabling security tools on request from email is unsafe.",
        ),
        _q(
            "Best habit when an email requests wire transfer changes?",
            ["Obey immediately to avoid delays", "Confirm with the vendor using a known phone/portal",
             "Reply all with bank details", "Ignore forever"], 1,
            "Verify payment changes out-of-band using known contacts.",
            "Email-only payment changes are a common fraud vector.",
        ),
    ],
    "password_cracker": [
        _q("Password: password", ["Weak", "Medium", "Strong"], 0,
           "Extremely common dictionary password — cracked instantly.",
           "Any list-based attack tries 'password' early."),
        _q("Password: qwerty", ["Weak", "Medium", "Strong"], 0,
           "Keyboard-walk passwords are in every cracking dictionary.",
           "Predictable keyboard patterns are weak."),
        _q("Password: Dragon!42", ["Weak", "Medium", "Strong"], 1,
           "Some complexity, but short and based on a common word + digits.",
           "Length and uniqueness matter more than a single symbol."),
        _q("Password: correct horse battery staple 2026!", ["Weak", "Medium", "Strong"], 2,
           "Long unique passphrase with extra entropy is strong for humans.",
           "Length from multiple unrelated words resists guessing."),
        _q("Reusing the same password on email and banking is risky because:",
           ["It is easier to remember, so it is safe", "One breach can compromise many accounts",
            "Banks prohibit unique passwords", "Reuse encrypts automatically"], 1,
           "Credential stuffing reuses leaked passwords across sites.",
           "Reuse links the fate of every account that shares the password."),
        _q("Which practice BEST improves password security?",
           ["Write one password on a sticky note on the monitor", "Use a password manager + unique passwords",
            "Share passwords in team chat", "Disable MFA to reduce friction"], 1,
           "Managers enable unique strong secrets without memorizing everything.",
           "Unique credentials limit blast radius from breaches."),
        _q("Password: 111111", ["Weak", "Medium", "Strong"], 0,
           "Repeated digits are trivial to guess.",
           "Low entropy sequences fall immediately."),
        _q("A 'password hint' that is your pet's name is risky because:",
           ["Hints are encrypted strongly", "Attackers often find that info from public posts",
            "Pets are random", "Hints disable MFA"], 1,
           "Public OSINT can reveal common hint answers.",
           "Hints should not be guessable from your public life."),
        _q("Why is length often more important than complexity rules alone?",
           ["Short complex passwords are always stronger", "Extra characters explode the search space",
            "Length removes the need for uniqueness", "Servers ignore long passwords"], 1,
           "Each added character multiplies brute-force difficulty.",
           "A long passphrase usually beats a short 'complex' word."),
        _q("Password: Letmein1", ["Weak", "Medium", "Strong"], 0,
           "Common phrase with a trailing digit — still dictionary material.",
           "Cracking tools include common phrases and digit suffixes."),
        _q("Offline hash cracking is easier when:",
           ["Hashes are salted uniquely", "Hashes use slow algorithms like bcrypt/argon2",
            "Hashes are unsalted and fast (e.g., raw MD5)", "MFA is enabled"], 2,
           "Fast unsalted hashes let attackers try billions of guesses quickly.",
           "Modern slow salted hashes slow offline attacks."),
        _q("Which is the strongest policy for admin accounts?",
           ["Shared admin password posted in wiki", "Unique long password + MFA + just-in-time access",
            "Same password as personal email", "No passwords, only SMS to a public channel"], 1,
           "Admin accounts need unique secrets, MFA, and limited standing privilege.",
           "Shared standing admin passwords are high-impact liabilities."),
        _q("Password: Spring2020!", ["Weak", "Medium", "Strong"], 1,
           "Season+year+symbol is a very common corporate pattern.",
           "Predictable seasonal passwords are medium at best."),
        _q("A passphrase of four random unrelated words is usually:",
           ["Weaker than 'P@ssw0rd'", "Stronger than short complex single words",
            "Illegal", "The same as a PIN"], 1,
           "Diceware-style passphrases trade memorability for length/entropy.",
           "Unrelated words beat a short mangled dictionary word."),
        _q("Changing passwords every 30 days without cause mainly:",
           ["Always increases security dramatically", "Can push users toward weaker predictable patterns",
            "Removes need for MFA", "Stops phishing entirely"], 1,
           "Forced frequent rotation often harms usability and uniqueness; change after compromise instead.",
           "Modern guidance favors long unique secrets + MFA over ritual monthly changes."),
    ],
    "network_defense": [
        _q("A firewall's primary job is to:",
           ["Make websites load faster", "Control traffic based on security rules",
            "Replace antivirus completely", "Encrypt hard drives"], 1,
           "Firewalls allow/deny traffic according to policy.",
           "Throughput is not the firewall's security purpose."),
        _q("Unusual overnight outbound transfers from a workstation may indicate:",
           ["Normal screensaver activity only", "Possible data exfiltration or malware",
            "That DNS is broken", "That printers need toner"], 1,
           "Anomalous egress volume/timing is a classic detection signal.",
           "Ignore high-volume night egress at your peril."),
        _q("Network segmentation helps by:",
           ["Putting all servers on one flat VLAN", "Limiting how far an attacker can move laterally",
            "Removing the need for patches", "Disabling logging"], 1,
           "Segments contain blast radius between trust zones.",
           "Flat networks make lateral movement easier."),
        _q("IDS/IPS primarily:",
           ["Detect/prevent suspicious network activity", "Replace backups",
            "Assign IP addresses", "Design logos"], 1,
           "Intrusion detection/prevention watches for malicious patterns.",
           "They are monitoring/control controls, not backup systems."),
        _q("Least privilege on network shares means:",
           ["Everyone gets full control", "Users get only the access they need",
            "Shares are public on the internet", "Passwords are optional"], 1,
           "Minimize access to reduce damage from compromised accounts.",
           "Broad share permissions amplify ransomware impact."),
        _q("A DMZ is typically used to:",
           ["Store employee payroll offline", "Host internet-facing services away from the internal LAN",
            "Disable all inbound traffic forever", "Hide the firewall"], 1,
           "DMZs isolate public services from trusted internal systems.",
           "Internet apps should not sit deep inside the LAN without controls."),
        _q("Port 22 commonly relates to:",
           ["HTTP web traffic", "SSH remote administration", "SMTP email delivery", "DNS queries"], 1,
           "SSH commonly uses TCP/22 for admin access — restrict and monitor it.",
           "Exposing admin ports widely increases risk."),
        _q("If a host is suspected compromised, a common first containment step is:",
           ["Post credentials in chat", "Isolate/segment the host from sensitive networks",
            "Disable all company email", "Ignore until Friday"], 1,
           "Containment limits damage while investigation continues.",
           "Leaving a suspect host fully connected risks spread."),
        _q("Egress filtering helps stop:",
           ["Only inbound spam", "Unauthorized outbound connections from internal hosts",
            "Monitor brightness issues", "Certificate expiry"], 1,
           "Controlling outbound traffic can block malware callbacks/exfil.",
           "Outbound allow-all policies hide many intrusions."),
        _q("Why log DNS queries in a SOC?",
           ["DNS is never abused", "Malware often uses DNS for C2 or tunneling",
            "DNS replaces MFA", "Logs slow attackers magically"], 1,
           "DNS telemetry reveals suspicious domains and covert channels.",
           "Blind spots in DNS hurt detection."),
        _q("Zero Trust networking emphasizes:",
           ["Trust anything inside the LAN", "Verify explicitly; never assume location equals trust",
            "Disable encryption", "Share one VPN account"], 1,
           "Identity, device, and context matter more than network location alone.",
           "Internal IP ≠ automatic trust."),
        _q("A sudden scan of many internal ports from one host suggests:",
           ["Harmless wallpaper change", "Reconnaissance / lateral movement attempt",
            "Successful patching", "Printer discovery only always"], 1,
           "Internal port scans are a strong investigation trigger.",
           "Treat unexpected internal scanning as hostile until proven otherwise."),
        _q("TLS on internal admin tools is important because:",
           ["Encryption is only for public websites", "Credentials and sessions can be sniffed on the LAN",
            "It removes authentication needs", "It blocks all malware"], 1,
           "Internal networks can still be monitored by attackers.",
           "Plaintext admin panels expose secrets."),
        _q("Rate limiting login endpoints helps against:",
           ["Backup failures", "Password spraying / brute force", "Cable clutter", "Color themes"], 1,
           "Throttling slows automated credential attacks.",
           "Unlimited login attempts invite spraying."),
        _q("Which is a healthier default firewall posture?",
           ["Allow all, deny rare exceptions", "Deny by default, allow required services",
            "Disable the firewall at night", "Open all ports to the world"], 1,
           "Default-deny reduces accidental exposure.",
           "Allow-all defaults are hard to secure later."),
    ],
    "cryptography": [
        _q("Confidentiality primarily means:",
           ["Data can be changed freely", "Only authorized parties can read the data",
            "Data is deleted weekly", "Backups are optional"], 1,
           "Encryption and access control protect confidentiality.",
           "Confidentiality is about unauthorized reading, not deletion."),
        _q("A digital signature mainly provides:",
           ["Faster downloads", "Integrity and authenticity of a message",
            "Free cloud storage", "Password hints"], 1,
           "Signatures bind content to a signer and detect tampering.",
           "They are not primarily about speed or storage."),
        _q("Why salt password hashes?",
           ["To make hashes prettier", "To prevent identical passwords from sharing one hash / slow rainbow tables",
            "To reverse hashes easily", "To remove MFA"], 1,
           "Unique salts defeat precomputed attacks and reveal duplicate passwords less easily.",
           "Unsalted databases leak password equality."),
        _q("Symmetric encryption uses:",
           ["Two different related keys for encrypt/decrypt", "The same key for encrypt and decrypt",
            "No keys at all", "Only public keys"], 1,
           "AES is a common symmetric cipher — key secrecy is critical.",
           "Symmetric ≠ public-key pairs."),
        _q("Public-key encryption is useful because:",
           ["Anyone can encrypt to you with your public key; only you decrypt with private key",
            "Public keys must stay secret", "Private keys should be emailed widely", "It removes integrity needs"], 0,
           "Asymmetric crypto enables secure key exchange and identity without sharing the private key.",
           "Never share private keys."),
        _q("HTTPS protects data in transit using:",
           ["TLS", "FTP only", "Unencrypted HTTP headers as secrets", "Clipboard history"], 0,
           "TLS provides encryption and server authentication for HTTPS.",
           "Plain HTTP exposes content on the path."),
        _q("Hashing a file before/after transfer helps check:",
           ["Color accuracy", "Integrity — whether bits changed", "Font size", "Battery health"], 1,
           "Matching hashes suggest the file was not altered in transit.",
           "Hashes do not by themselves prove who sent the file."),
        _q("Storing encryption keys in the same chat as ciphertext is bad because:",
           ["Chats are always air-gapped", "Anyone who sees both can decrypt",
            "Keys must be public", "Ciphertext needs no key"], 1,
           "Key separation and access control are fundamental.",
           "Co-locating keys defeats encryption."),
        _q("AES-GCM provides:",
           ["Only compression", "Confidentiality plus integrity (authenticated encryption)",
            "Virus removal", "Domain registration"], 1,
           "Authenticated modes detect tampering while encrypting.",
           "Encryption without integrity can be dangerous."),
        _q("A Caesar cipher is weak today mainly because:",
           ["It uses quantum computers only", "Tiny key space is trivial to brute force",
            "It requires AES hardware", "It cannot shift letters"], 1,
           "Classic substitution ciphers are teaching tools, not modern protection.",
           "Do not rely on Caesar for real secrets."),
        _q("Key rotation matters because:",
           ["Keys improve with age automatically", "Limiting key lifetime reduces damage if a key leaks",
            "Rotation removes authentication", "Public keys must never change"], 1,
           "Compromise windows shrink when keys are rotated responsibly.",
           "Eternal keys are high-impact secrets."),
        _q("End-to-end encryption means:",
           ["Provider can always read plaintext", "Only endpoints hold keys needed to read content",
            "No authentication exists", "Metadata never exists"], 1,
           "E2EE keeps intermediaries from reading message bodies.",
           "Providers may still see metadata."),
        _q("Using MD5 to store modern passwords is bad because:",
           ["MD5 is too slow", "MD5 is fast and broken for password storage",
            "MD5 is a symmetric cipher", "MD5 requires public keys"], 1,
           "Use purpose-built password KDFs (bcrypt/scrypt/argon2), not raw MD5.",
           "Fast hashes accelerate offline cracking."),
        _q("Certificate pinning helps apps by:",
           ["Trusting any certificate", "Reducing risk from rogue/misissued certificates for known endpoints",
            "Removing TLS", "Sharing private keys with users"], 1,
           "Pinning constrains which certs an app will trust.",
           "It is an advanced hardening technique with operational tradeoffs."),
        _q("Random IVs/nonces in encryption are important to:",
           ["Make ciphertext patterns repeat usefully for attackers", "Avoid leaking patterns when encrypting similar messages",
            "Delete private keys", "Replace passwords"], 1,
           "Reuse of IVs/nonces can catastrophically weaken many modes.",
           "Fresh unpredictability protects repeated messages."),
    ],
    "osint": [
        _q("OSINT stands for collecting intelligence from:",
           ["Only classified military databases", "Publicly available sources",
            "Private phone taps only", "Guesswork without sources"], 1,
           "Open-source intelligence uses public/legal sources.",
           "OSINT is not a license for illegal access."),
        _q("Before concluding two online profiles are the same person, you should:",
           ["Assume matching display names are enough", "Corroborate with multiple independent signals",
            "Publish private addresses", "Ignore timestamps"], 1,
           "Name collisions are common — seek stronger correlation.",
           "Single weak signals cause false positives."),
        _q("A tip from an anonymous forum with no corroboration should be treated as:",
           ["Court-ready proof", "Low-reliability until verified",
            "More trusted than official docs", "A reason to dox someone"], 1,
           "Source reliability assessment is core to OSINT tradecraft.",
           "Unverified tips are hypotheses, not findings."),
        _q("Checking whether a claimed post predates an incident helps assess:",
           ["Font choice", "Timeline consistency / reliability of the claim",
            "Wi-Fi password strength", "CPU temperature"], 1,
           "Temporal correlation can refute weak claims.",
           "Out-of-order timelines undermine tips."),
        _q("Ethical OSINT practice forbids:",
           ["Reading public news", "Stalking, doxxing, or illegally accessing private accounts",
            "Archiving public pages per policy", "Citing sources"], 1,
           "Stay within law and ethics — public ≠ anything-goes.",
           "Private intrusion is out of scope for CyberQuest OSINT."),
        _q("Username reuse across sites is:",
           ["Proof of guilt alone", "A weak-to-moderate lead needing more corroboration",
            "Always fake", "A decryption key"], 1,
           "Handles can be coincidental or intentionally mimicked.",
           "Treat reuse as a lead, not a verdict."),
        _q("Why archive/public-capture responsibly during investigations?",
           ["To alter evidence quietly", "To preserve what was publicly visible at a point in time",
            "To obtain private DMs", "To bypass MFA"], 1,
           "Content changes; lawful preservation supports analysis.",
           "Preservation ≠ hacking private systems."),
        _q("Reverse image search on a profile photo may show:",
           ["Bank passwords", "Whether the image is a reused stock/stolen photo",
            "Private GPS of your neighbors automatically", "Wi-Fi PSKs"], 1,
           "Image reuse can indicate sockpuppets or stolen pics.",
           "It does not magically reveal secrets."),
        _q("Domain WHOIS privacy on a site usually means:",
           ["The site is definitely malicious", "Registrant details may be hidden — inconclusive alone",
            "HTTPS is broken", "OSINT is impossible"], 1,
           "Privacy redaction is common and not proof of wrongdoing.",
           "Combine with other signals."),
        _q("When writing an OSINT finding you should:",
           ["State certainty without evidence", "Separate facts, inferences, and confidence level",
            "Omit sources", "Include private credentials you found"], 1,
           "Clear analytic hygiene prevents overclaiming.",
           "Document what you know vs what you guess."),
        _q("Geolocating a photo ethically relies on:",
           ["Breaking into cameras", "Visible public landmarks/context — not illegal tracking devices",
            "Buying stolen phone data", "Guessing without notes"], 1,
           "Use visible public cues and document uncertainty.",
           "Illegal tracking is prohibited."),
        _q("A sockpuppet account is:",
           ["A verified government portal", "A fake/alt identity used to deceive or amplify",
            "An MFA token", "A firewall rule"], 1,
           "Detect via inconsistencies, reused assets, and behavior patterns.",
           "Do not harass suspected sockpuppets."),
        _q("Cross-checking the same claim across independent outlets helps:",
           ["Create circular reporting risks if they copy each other", "Increase confidence when sources are truly independent",
            "Replace all technical analysis", "Prove intent automatically"], 1,
           "Independent corroboration strengthens findings; copy-paste networks do not.",
           "Watch for circular amplification."),
        _q("Metadata stripped from an image means:",
           ["The image is fake for sure", "EXIF may be unavailable — use other public cues",
            "You should demand private data", "OSINT must stop"], 1,
           "Missing EXIF is common; continue with careful open methods.",
           "Absence of metadata is not proof of authenticity or fraud alone."),
        _q("The best closing action for a weak public tip is:",
           ["Accuse the person publicly", "Document insufficient evidence and stop at public sources",
            "Hack their email to be sure", "Publish home addresses"], 1,
           "Responsible reporting beats harmful overreach.",
           "CyberQuest OSINT ends at lawful public analysis."),
    ],
}


def iter_seed_questions():
    """Yield question dicts for all set courses (legacy QUIZ_GAMES + extras)."""
    for course, meta_questions in EXTRA_POOL.items():
        # Originals from QUIZ_GAMES first
        for q in QUIZ_GAMES.get(course, {}).get("questions", []):
            yield {
                "course": course,
                "prompt": q["prompt"],
                "options": list(q["options"]),
                "correct_index": q["correct_index"],
                "explanation": q["explanation"],
                "correct_feedback": "Correct!",
                "wrong_feedback": (
                    f"Incorrect. The correct answer is: {q['options'][q['correct_index']]}. "
                    f"{q['explanation']}"
                ),
            }
        for q in meta_questions:
            yield {"course": course, **q}
