"""
Django settings for cyberquest project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: don't run with debug turned on in production!
# Default False; set DEBUG=True in local .env for development.
DEBUG = _env_bool("DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# Never hard-code a real production secret. Local DEBUG may use a clearly
# insecure fallback so `runserver` works after copying .env.example.
SECRET_KEY = (os.environ.get("SECRET_KEY") or "").strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-local-development-only-key"
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is required when DEBUG is False."
        )

# Local defaults keep localhost development working. Production hosts come from
# ALLOWED_HOSTS and/or Render's RENDER_EXTERNAL_HOSTNAME — no invented domains.
_allowed = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]
ALLOWED_HOSTS = _allowed or ["localhost", "127.0.0.1"]

# Render provides this automatically.
RENDER_EXTERNAL_HOSTNAME = (os.environ.get("RENDER_EXTERNAL_HOSTNAME") or "").strip()
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Render sets RENDER_EXTERNAL_HOSTNAME on the web service. Only then is the
# rightmost X-Forwarded-For address (the one Render appended) a client IP.
# Direct local requests keep using REMOTE_ADDR and ignore forwarded headers.
BEHIND_RENDER_PROXY = bool(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]
if RENDER_EXTERNAL_HOSTNAME:
    _render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if _render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_render_origin)
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'dashboard',
    'courses',
    'games',
    'achievements',
    'pages',
    'notifications',
    'leaderboard',
    'certificates',
    'practice',
    'question_bank',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'cyberquest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates", BASE_DIR / "home page"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cyberquest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# Shared across Gunicorn workers and still present after a process restart.
# LocMemCache is per-process, so login limits and verification-code attempt
# counters would reset on every worker. The table is created by migration.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "cyberquest_cache",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'accounts.validators.SpecialCharacterValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
    ("home_page", BASE_DIR / "home page"),
    ("vendor/page-flip", BASE_DIR / "node_modules" / "page-flip" / "dist" / "js"),
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Manifest hashing is for production collectstatic. Local/DEBUG must
        # not require a pre-built manifest (keeps runserver and tests working).
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# ---- User-uploaded files (profile pictures, etc.) ----
# Different from STATIC_URL/STATIC_ROOT above: those are OUR css/js files,
# these are files USERS upload at runtime (e.g. profile pictures).
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ---- Custom auth ----
AUTH_USER_MODEL = 'accounts.CustomUser'
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]
LOGIN_URL = '/accounts/login/'

# ---- Email (development: prints to terminal instead of really sending) ----
# To send REAL emails later (e.g. via Gmail SMTP), change EMAIL_BACKEND to
# 'django.core.mail.backends.smtp.EmailBackend' and set EMAIL_HOST,
# EMAIL_HOST_USER, EMAIL_HOST_PASSWORD (use a Gmail "App Password", not your
# real password) -- keep those in a .env file, never hardcoded here.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL_ADDRESS')

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET')

# ---- AI Question Bank (Gemini) ----
# Never expose these values to the browser / Next.js client.
AI_PROVIDER = os.environ.get('AI_PROVIDER', 'gemini')
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-3.5-flash-lite')
# Comma-separated fallbacks used when the primary model is overloaded (503/high demand).
GEMINI_MODEL_FALLBACKS = os.environ.get(
    'GEMINI_MODEL_FALLBACKS',
    'gemini-3.1-flash-lite,gemini-3.5-flash,gemini-3.6-flash,gemini-flash-lite-latest',
)
AI_GENERATION_TIMEOUT = int(os.environ.get('AI_GENERATION_TIMEOUT', '180'))
AI_GENERATION_MAX_ATTEMPTS = int(os.environ.get('AI_GENERATION_MAX_ATTEMPTS', '2'))
AI_GENERATION_TEMPERATURE = float(os.environ.get('AI_GENERATION_TEMPERATURE', '0.4'))
AI_NEAR_DUPLICATE_THRESHOLD = float(os.environ.get('AI_NEAR_DUPLICATE_THRESHOLD', '0.88'))
AI_MAX_REPAIR_ATTEMPTS = int(os.environ.get('AI_MAX_REPAIR_ATTEMPTS', '3'))

# Public site origin for certificate QR verification links (no trailing slash).
# Example on Render: https://your-app.onrender.com
# Falls back to the incoming request host when unset.
PUBLIC_BASE_URL = os.environ.get('PUBLIC_BASE_URL', '').rstrip('/')

# ---- Production HTTPS / cookie hardening (DEBUG keeps local HTTP working) ----
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True
    )
    SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", default=True)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
