"""
Django settings for cyberquest project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wl908#^e)12ktl$&l&3zepdx2n_+vy85o_u#(6_%d8s80bu(0p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- Our custom feature apps (each one is fully separate/removable) ---
    'accounts',        # handles login, logout, custom user model
    'dashboard',       # handles the post-login home screen
    'courses',         # handles the cyber course intro / retro landing page
    'games',           # handles playable training simulations
]

# Tell Django to use OUR custom User model (email-based) instead of the
# default username-based one. This points to the model we'll create in
# accounts/models.py
AUTH_USER_MODEL = 'accounts.CustomUser'

# Tell Django to use OUR custom authentication backend (checks email domain
# rules etc.) instead of only the default one. Defined in accounts/backends.py
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend',  # fallback (e.g. for admin)
]

# Where Django sends a user after a successful login
LOGIN_REDIRECT_URL = '/dashboard/'

# Where Django sends a user if they try to access a @login_required page
# without being logged in
LOGIN_URL = '/accounts/login/'

# Where Django sends a user after logout
LOGOUT_REDIRECT_URL = '/accounts/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cyberquest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cyberquest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cyberquest_db',        # the MySQL database you'll create
        'USER': 'root',                  # your MySQL username
        'PASSWORD': '7726@San',                  # your MySQL password (blank if none set)
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',        # supports emojis / all unicode safely
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Django automatically looks inside each installed app's own "static/" folder
# (e.g. accounts/static/accounts/css/login.css) thanks to 'django.contrib.staticfiles'
# and APP_DIRS=True on templates. This is what lets us keep every page's CSS
# in its own separate folder instead of one global stylesheet.
STATICFILES_DIRS = []  # (only needed if you add a project-level "static/" folder later)
