# Generated by Django 6.0.7 on 2026-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageVisitDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('visits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['day'], name='pages_homep_day_593311_idx')],
            },
        ),
    ]
