from django.urls import path
from django.views.generic import RedirectView

from . import ops_certificate_templates, ops_views

app_name = "ops"

urlpatterns = [
    path("", ops_views.overview, name="overview"),
    path("students/", ops_views.students, name="students"),
    path("students/<int:pk>/", ops_views.student_detail, name="student"),
    path("students/<int:pk>/status/", ops_views.student_status, name="student_status"),
    path("courses/", ops_views.courses, name="courses"),
    path("courses/new/", ops_views.course_create, name="course_create"),
    path("courses/<str:code>/", ops_views.course_edit, name="course_edit"),
    path("courses/<str:code>/publish/", ops_views.course_publish, name="course_publish"),
    path("games/", ops_views.games, name="games"),
    path("games/<slug:key>/", ops_views.game_page, name="game"),
    path("practice/", ops_views.practice, name="practice"),
    path("practice/<slug:key>/", ops_views.practice_scenario, name="practice_scenario"),
    path("questions/", ops_views.questions, name="questions"),
    path("questions/bank/<int:pk>/", ops_views.question_bank_detail, name="question_bank"),
    path("questions/bank/<int:pk>/archive/", ops_views.archive_bank, name="archive_bank"),
    path("questions/item/<int:pk>/", ops_views.question_detail, name="question_detail"),
    path("questions/item/<int:pk>/visibility/", ops_views.question_visibility, name="question_visibility"),
    path("review/", ops_views.review, name="review"),
    path("review/<int:pk>/approve/", ops_views.approve_bank, name="approve_bank"),
    path("review/set/<int:pk>/reject/", ops_views.reject_set, name="reject_set"),
    path("certificates/", ops_views.certificates, name="certificates"),
    path("certificates/templates/", ops_certificate_templates.template_list, name="certificate_templates"),
    path("certificates/templates/new/", ops_certificate_templates.template_create, name="certificate_template_new"),
    path("certificates/templates/<int:pk>/", ops_certificate_templates.template_edit, name="certificate_template_edit"),
    path("certificates/templates/<int:pk>/activate/", ops_certificate_templates.template_activate, name="certificate_template_activate"),
    path("certificates/templates/<int:pk>/deactivate/", ops_certificate_templates.template_deactivate, name="certificate_template_deactivate"),
    path("certificates/templates/<int:pk>/delete/", ops_certificate_templates.template_delete, name="certificate_template_delete"),
    path("certificates/templates/<int:pk>/artwork.png", ops_certificate_templates.template_artwork, name="certificate_template_artwork"),
    path("certificates/templates/<int:pk>/preview.png", ops_certificate_templates.template_sample_preview, name="certificate_template_preview"),
    path("certificates/issue/<int:pk>/", ops_views.issue_certificate, name="certificate_issue"),
    path("certificates/<int:pk>/", ops_views.certificate_detail, name="certificate"),
    path("achievements/", ops_views.achievements, name="achievements"),
    path("achievements/<int:pk>/", ops_views.achievement_detail, name="achievement"),
    path("leaderboard/", ops_views.leaderboard, name="leaderboard"),
    path("notifications/", ops_views.notifications, name="notifications"),
    path("notifications/<int:pk>/", ops_views.notification_detail, name="notification"),
    path("contacts/", ops_views.contact, name="contact"),
    path("contacts/<int:pk>/", ops_views.contact_detail, name="contact_message"),
    path("contacts/<int:pk>/resolve/", ops_views.resolve_contact, name="resolve_contact"),
    path("contacts/<int:pk>/reply/", ops_views.reply_contact, name="reply_contact"),
    path("contact/", RedirectView.as_view(pattern_name="ops:contact", query_string=True)),
    path("contact/<int:pk>/resolve/", ops_views.resolve_contact),
    path("search/", ops_views.search, name="search"),
    path("analytics/", ops_views.analytics, name="analytics"),
    path("settings/", ops_views.settings_page, name="settings"),
    path("settings/administrators/new/", ops_views.create_administrator, name="create_administrator"),
]
