# Generated by Django 6.0.7 on 2026-09-02 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(help_text="e.g. 'Head of CyberQuest' or 'Founder & Director'", max_length=150)),
                ('signature_image', models.ImageField(help_text='A scanned/photographed signature, ideally on a transparent or white background.', upload_to='signatures/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Left-to-right display order on the certificate.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive signatories are omitted from new certificates.')),
            ],
            options={
                'verbose_name_plural': 'Signatories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=30, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
