# Generated by Django 6.0.7 on 2026-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_template_pdf_jpg_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive signatories are omitted from newly generated default certificates.'),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Left-to-right display order on the default certificate.'),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='title',
            field=models.CharField(help_text="e.g. 'Head of CyberQuest' or 'Course Director'", max_length=150),
        ),
    ]
