# Generated by Django 6.0.7 on 2026-07-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_cyber_class_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course_intro_completed',
            field=models.BooleanField(default=False),
        ),
    ]
