# Generated by Django 6.0.7 on 2026-08-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional avatar shown on the dashboard and profile. Falls back to a letter-avatar (first letter of the username) if not set.', null=True, upload_to='profile_pictures/'),
        ),
    ]
