# Generated by Django 6.0.7 on 2026-08-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_google_linked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
