# Generated by Django 6.0.7 on 2026-10-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_email_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=True, help_text='False until a password signup confirms ownership of the email. Existing and Google accounts stay verified.'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('login_2fa', 'Login Verification'), ('password_reset', 'Password Reset'), ('email_signup', 'Signup Email Verification')], max_length=20),
        ),
    ]
