# Generated by Django 6.0.7 on 2026-07-31 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short identifier shown in the UI, e.g. MOD-01', max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(help_text='One-line summary shown on the course list page.', max_length=250)),
                ('content', models.TextField(help_text="The full lesson content shown on the course's reading page. Plain text/paragraphs -- line breaks are preserved automatically.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order on the course list page (lowest first).')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished courses are hidden from users but kept in the admin panel.')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
