# Generated by Django 6.0.7 on 2026-10-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional cover image shown on course cards (JPG, PNG, WEBP, or GIF, up to 2 MB).', null=True, upload_to='course_thumbnails/'),
        ),
    ]
