# Generated by Django 6.0.7 on 2026-09-18 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('phishing', 'Phishing'), ('password', 'Password Security'), ('network', 'Network Defense'), ('cryptography', 'Cryptography'), ('osint', 'OSINT Investigation')], max_length=20)),
                ('activity_type', models.CharField(choices=[('game', 'Game'), ('simulation', 'Simulation'), ('incident', 'Incident')], max_length=20)),
                ('scenario_key', models.CharField(max_length=80)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('result_summary', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
