# Generated by Django 6.0.7 on 2026-09-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
