# Generated by Django 6.0.7 on 2026-08-21 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.CharField(choices=[('phishing_simulator', 'Phishing Simulator'), ('password_cracker', 'Password Cracker Challenge'), ('whack_a_phish', 'Whack-a-Phish'), ('network_defense', 'Network Defense'), ('cryptography', 'Cryptography Challenge'), ('osint', 'OSINT Investigation'), ('steganography', 'Steganography Hunt')], max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
