# Generated by Django 6.0.7 on 2026-08-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameattempt',
            options={},
        ),
        migrations.AlterField(
            model_name='gameattempt',
            name='game_key',
            field=models.CharField(choices=[('phishing_simulator', 'Phishing Simulator'), ('password_cracker', 'Password Cracker Challenge'), ('whack_a_phish', 'Whack-a-Phish'), ('network_defense', 'Network Defense')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gameattempt',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gameattempt',
            name='total_questions',
            field=models.PositiveIntegerField(),
        ),
    ]
