# Generated by Django 6.0.7 on 2026-08-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gameattempt_options_alter_gameattempt_game_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameattempt',
            name='game_key',
            field=models.CharField(choices=[('phishing_simulator', 'Phishing Simulator'), ('password_cracker', 'Password Cracker Challenge'), ('whack_a_phish', 'Whack-a-Phish'), ('network_defense', 'Network Defense'), ('cryptography', 'Cryptography Challenge'), ('osint', 'OSINT Investigation'), ('steganography', 'Steganography Hunt')], max_length=50),
        ),
    ]
