# Generated by Django 6.0.7 on 2026-09-19 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gameattempt_game_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('phishing_simulator', 'Phishing'), ('password_cracker', 'Password Security'), ('network_defense', 'Network Defense'), ('cryptography', 'Cryptography'), ('osint', 'OSINT')], db_index=True, max_length=50)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(help_text='List of answer option strings.')),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('explanation', models.TextField(help_text='Explanation shown after answering (esp. when correct).')),
                ('correct_feedback', models.TextField(blank=True, help_text="Short message when the learner is correct. Defaults to 'Correct!' if blank.")),
                ('wrong_feedback', models.TextField(blank=True, help_text='Message when wrong — why the choice fails. Defaults to a standard incorrect line if blank.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('phishing_simulator', 'Phishing'), ('password_cracker', 'Password Security'), ('network_defense', 'Network Defense'), ('cryptography', 'Cryptography'), ('osint', 'OSINT')], db_index=True, max_length=50)),
                ('set_number', models.PositiveSmallIntegerField()),
                ('set_type', models.CharField(choices=[('ADMIN', 'Admin-created'), ('AUTO', 'System-generated')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course', 'set_number'],
            },
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='set_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='set_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='games.questionset'),
        ),
        migrations.CreateModel(
            name='QuestionSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_items', to='games.question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.questionset')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('question_set', 'question')},
            },
        ),
        migrations.AddField(
            model_name='questionset',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='sets', through='games.QuestionSetItem', to='games.question'),
        ),
        migrations.AlterUniqueTogether(
            name='questionset',
            unique_together={('course', 'set_number')},
        ),
    ]
