# Generated by Django 6.0.7 on 2026-09-21 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_question_questionset_gameattempt_set_number_and_more'),
        ('question_bank', '0001_ai_question_bank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='generated_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('simulation', 'Simulation'), ('true_false', 'True / False')], db_index=True, default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='scenario_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='source_evidence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='source_excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='source_section',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='questionset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questionset',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='question_bank.questionbank'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='APPROVED', help_text='Bank-backed sets start as REVIEW; legacy sets remain APPROVED.', max_length=20),
        ),
        migrations.AddField(
            model_name='questionset',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='set_type',
            field=models.CharField(choices=[('ADMIN', 'Admin-created'), ('AUTO', 'System-generated'), ('NORMAL', 'Normal knowledge'), ('SIMULATION', 'Simulation')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.UniqueConstraint(condition=models.Q(('question_bank__isnull', True)), fields=('course', 'set_number'), name='games_qset_legacy_course_setnum_uniq'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.UniqueConstraint(condition=models.Q(('question_bank__isnull', False)), fields=('question_bank', 'set_number'), name='games_qset_bank_setnum_uniq'),
        ),
    ]
