# Generated by Django 6.0.7 on 2026-09-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_ai_question_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameattempt',
            name='selected_question_ids',
            field=models.JSONField(blank=True, default=list, help_text='Ordered question PKs when the attempt used balanced difficulty×type selection.'),
        ),
    ]
