# Generated by Django 6.0.7 on 2026-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_balanced_selection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameattempt',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gameattempt',
            name='game_key',
            field=models.CharField(choices=[('phishing_simulator', 'Phishing Simulator'), ('password_cracker', 'Password Cracker Challenge'), ('whack_a_phish', 'Whack-a-Phish'), ('network_defense', 'Network Defense'), ('cryptography', 'Cryptography Challenge'), ('osint', 'OSINT Investigation'), ('steganography', 'Steganography Hunt')], db_index=True, max_length=50),
        ),
    ]
